### ISSUE TITLE
Help needed to generate MagicLinks

### ISSUE THREAD

**Issue by oleggrib** [TokenScript/attestation#242]
my steps:
- gradle build
- gradle shadowJar
- cd build/libs/
- openssl ecparam -name secp256k1 -genkey -noout -out key.pem

then: (console input/output)

```
olehhryb@ libs % java -version
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
olehhryb@ libs % node -v
v16.14.2
olehhryb@ libs % java -cp ./attestation-0.3.16-all.jar org.devcon.ticket.Issuer ./key.pem oleg@oleg.com 11 22 33
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/devcon/ticket/Issuer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

@jot2re , can you help me to solve issue and generate MagicLink?

**Comment by jot2re** [comment]
I think the issue is that you are using Java 8, the code needs at least Java 11 and also seems to have been compiled with a java compiler of at least version 11. 
You need to change the java runtime version. If you use Windows then there is a guide [here](https://superuser.com/questions/262757/changing-current-version-of-java-within-windows)

**Comment by oleggrib** [comment]
thank you, it works great. I just have to update negotiator to support new ticket format.
